name: Deploy

# Controls when the action will run.
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/shreyash/PayNow-backend

            # Install Node.js if not already installed
            if ! command -v node &> /dev/null; then
              echo "Node.js not found. Installing..."
              curl -sL https://deb.nodesource.com/setup_16.x | bash -
              sudo apt-get install -y nodejs
            else
              echo "Node.js is already installed"
            fi

            # Install PM2 if not already installed
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found. Installing..."
              sudo npm install -g pm2
            else
              echo "PM2 is already installed"
            fi

            # Pull the latest changes and install dependencies
            git pull origin main
            npm install

            # Restart the app using PM2
            pm2 restart all
